- alias: Andrew is home
  trigger:
  - platform: state
    entity_id: group.tracker_andrew
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: notify.slack
    data:
      message: Andrew is home
  - service: homeassistant.turn_on
    entity_id: scene.evening
  id: a79d7a7d8d3d4494ba806e4bdf4a63e7
- alias: Send roomba home when Andrew comes home
  trigger:
  - platform: state
    entity_id: group.tracker_andrew
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: vacuum.roomba
    state: 'on'
  action:
  - service: vacuum.return_to_base
    entity_id: vacuum.roomba
  id: ed717fd547ca40dd98b8c5ccb7fe3544
- alias: Close the blinds when the sun has set
  trigger:
  - platform: sun
    event: sunset
    offset: 00:00:00
  action:
  - service: cover.close_cover
    entity_id: cover.blinds
- alias: Open the blinds a little when I wake up
  trigger:
  - platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: goodmorning
  action:
  - service: cover.set_cover_position
    entity_id: cover.blinds
    position: 20
- alias: Turn on lights when the sun sets and I am home
  trigger:
  - platform: sun
    event: sunset
    offset: -00:45:00
  condition:
  - condition: state
    entity_id: group.tracker_andrew
    state: home
  action:
  - service: homeassistant.turn_on
    entity_id: scene.evening
  - service: notify.slack
    data:
      message: The sun is setting soon and you're home so I turned the lights on
  id: eb5645437abf48c886421a0fdb48fdc1
- alias: evening2
  trigger:
  - platform: sun
    event: sunset
    offset: 00:15:00
  condition:
  - condition: state
    entity_id: group.tracker_andrew
    state: home
  action:
  - service: homeassistant.turn_on
    entity_id: scene.Evening2
  id: 69a0c511e1e54f3c9d0c05e03a42bf59
- alias: evening3
  trigger:
  - platform: sun
    event: sunset
    offset: 00:45:00
  condition:
  - condition: state
    entity_id: group.tracker_andrew
    state: home
  action:
  - service: homeassistant.turn_on
    entity_id: scene.Evening3
  id: 7e777b1fd90a47d9992e39697723e852
- alias: evening4
  trigger:
  - platform: sun
    event: sunset
    offset: 01:15:00
  condition:
  - condition: state
    entity_id: group.tracker_andrew
    state: home
  action:
  - service: homeassistant.turn_on
    entity_id: scene.Evening4
  id: 9d3952a62f2544caac2f69156ef78ff2
- alias: evening5
  trigger:
  - platform: sun
    event: sunset
    offset: 01:45:00
  condition:
  - condition: state
    entity_id: group.tracker_andrew
    state: home
  action:
  - service: homeassistant.turn_on
    entity_id: scene.Evening5
  id: 80f82879d29e4c0eba747bf4f446cf7d
- alias: evening6
  trigger:
  - platform: sun
    event: sunset
    offset: 02:15:00
  condition:
  - condition: state
    entity_id: group.tracker_andrew
    state: home
  action:
  - service: homeassistant.turn_on
    entity_id: scene.Evening6
  id: 03d0091b8a87455fadca91e74a98be80
- alias: evening7
  trigger:
  - platform: sun
    event: sunset
    offset: 02:45:00
  condition:
  - condition: state
    entity_id: group.tracker_andrew
    state: home
  action:
  - service: homeassistant.turn_on
    entity_id: scene.Evening7
  id: 8b91e33f8ff846e98bcc3213ea2383e8
- alias: evening8
  trigger:
  - platform: sun
    event: sunset
    offset: 03:15:00
  condition:
  - condition: state
    entity_id: group.tracker_andrew
    state: home
  action:
  - service: homeassistant.turn_on
    entity_id: scene.Evening8
  id: f22f9438a104486da4a4d6ceeaaecb36
- alias: evening9
  trigger:
  - platform: sun
    event: sunset
    offset: 03:45:00
  condition:
  - condition: state
    entity_id: group.tracker_andrew
    state: home
  action:
  - service: homeassistant.turn_on
    entity_id: scene.Evening9
  id: de3f2e90c9ad47beb98bc79376af0cd0
- alias: evening10
  trigger:
  - platform: sun
    event: sunset
    offset: 04:15:00
  condition:
  - condition: state
    entity_id: group.tracker_andrew
    state: home
  action:
  - service: homeassistant.turn_on
    entity_id: scene.Evening10
  id: 0a26026b0dad41958cd91ffa93cd85b8
- alias: Turn off the lights when I leave home
  trigger:
  - platform: state
    entity_id: group.tracker_andrew
    from: home
    to: not_home
  action:
  - service: homeassistant.turn_off
    entity_id: group.all_lights
  - service: homeassistant.turn_off
    entity_id: switch.living_room
  - service: ifttt.trigger
    data:
      event: light_living_room_off
  - service: notify.slack
    data:
      message: You left home so I turned the lights off
  id: 2155018ca7674665b1cce7b4b2c20b8d
- alias: Open the blinds when I leave home
  trigger:
  - platform: state
    entity_id: group.tracker_andrew
    from: home
    to: not_home
  action:
  - service: cover.open_cover
    entity_id: cover.blinds
- id: 09eba6d35c8f477c97f2c6659c9078b6
  alias: Turn on the kitchen light in the morning
  trigger:
  - event: sunrise
    platform: sun
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: group.tracker_andrew
      state: home
  action:
  - service: homeassistant.turn_on
    entity_id: scene.morning
  - data:
      message: Good morning, I turned the lights on in the kitchen
    service: notify.slack
- alias: Rainy Day
  trigger:
  - platform: state
    entity_id: sensor.precip_intensity
    to: rain
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: group.tracker_andrew
      state: home
  - condition: time
    after: '14:00'
    before: '23:00'
  action:
  - service: homeassistant.turn_on
    entity_id: scene.evening
  - service: notify.slack
    data:
      message: It's raining so I turned the lights on
  id: 89d2a9c66dea4507bcc46577a06f84a6
- alias: Dark Morning
  trigger:
  - platform: numeric_state
    entity_id: sensor.dark_sky_cloud_coverage_0
    above: 70
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: group.tracker_andrew
      state: home
  - condition: state
    entity_id: sun.sun
    state: above_horizon
  action:
  - service: homeassistant.turn_on
    entity_id: scene.evening
  - service: notify.slack
    data:
      message: It's dark so I turned the lights on
  id: 169872498dae436589551c9a165da5b4
- alias: Begin vacuuming
  trigger:
  - platform: time
    at: '11:00:00'
  condition:
  - condition: state
    entity_id: group.tracker_andrew
    state: not_home
  action:
  - service: vacuum.turn_on
    entity_id: vacuum.roomba
  - service: notify.slack
    data:
      message: I started the Roomba on a cleaning cycle
  id: 3347c518a2cf4147a9c728c11ad2852f
- alias: TV On - Received IFTTT Webhook
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: tv_on
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
      source: Home
  id: eea9f741e0b94369b04e243f50616375
- alias: Open Youtube - Received IFTTT Webhook
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: tv_open_youtube
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
      source: YouTube
  id: 894327b1bb764cffb3a2f8849cfb1647
- alias: Open HBO Now - Received IFTTT Webhook
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: tv_open_hbonow
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
      source: HBO NOW
  id: d9af42d31d6149de80d3bf104860dfa2
- alias: Open Netflix - Received IFTTT Webhook
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: tv_open_netflix
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
      source: Netflix
  id: c521d7eef16946fcbc1ecfcf9d1acd59
- alias: Open Hulu - Received IFTTT Webhook
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: tv_open_hulu
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
      source: Hulu
  id: 88d18e69051c41e186f45996a9588c84
- alias: Open Prime Video - Received IFTTT Webhook
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: tv_open_primevideo
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
      source: Prime Video
  id: a9a05a2ab9d847fb9f66285e703d769d
- alias: Select theme
  id: hass_theme
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_select.hass_theme
  action:
  - service: frontend.set_theme
    data_template:
      name: '{{ states.input_select.hass_theme.state }}'
- alias: Turn off the lights when I go to sleep
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: group.tracker_andrew
      state: home
  trigger:
  - platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: goodnight
  action:
  - service: homeassistant.turn_off
    entity_id: group.all_lights
  id: 1f8c980eff8d44fbad564d5ccee0307d
- alias: Light show
  id: light_show
  trigger:
  - platform: state
    entity_id: group.tracker_andrew
    from: not_home
    to: home
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: group.tracker_andrew
      state: home
  action:
  ## 1
  - service: light.turn_on
    entity_id: light.bedroom
  - service: light.turn_on
    data_template:
      entity_id: light.bedroom
      brightness: 1
      rgb_color:
      - 255
      - 0
      - 255
  - service: light.turn_on
    data_template:
      entity_id: light.kitchen
      brightness: 1
      rgb_color:
      - 255
      - 0
      - 255
  - service: light.turn_on
    data_template:
      entity_id: light.lounge
      brightness: 1
      rgb_color:
      - 255
      - 0
      - 0
  ## 2
  - service: light.turn_on
    data_template:
      entity_id: light.kitchen
      brightness: 255
      transition: 2
      rgb_color:
      - 255
      - 0
      - 255
  - service: light.turn_on
    data_template:
      entity_id: light.bedroom
      brightness: 255
      transition: 2
      rgb_color:
      - 0
      - 255
      - 255
  - service: light.turn_on
    data_template:
      entity_id: light.lounge
      brightness: 255
      transition: 2
      rgb_color:
      - 255
      - 0
      - 255
  ## 3
  - service: light.turn_on
    data_template:
      entity_id: light.bedroom
      brightness: 89
      color_name: "Warm White"
  - service: light.turn_on
    data_template:
      entity_id: light.kitchen
      brightness: 89
      color_name: "Warm White"
  - service: light.turn_on
    data_template:
      entity_id: light.lounge
      brightness: 89
      color_name: "Warm White"