- alias: Close the blinds when I get home
  trigger:
  - platform: state
    entity_id: person.andrew
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: cover.close_cover
    entity_id: cover.blinds

- alias: Lights up (pre-sunset)
  trigger:
  - platform: time_pattern
    minutes: /1
  condition:
  - condition: state
    entity_id: person.andrew
    state: home
  - condition: sun
    after: sunset
    after_offset: "-01:00:00"
  - condition: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 10
    above: 0
  action:
  - service: light.turn_on
    entity_id: light.main_lights
    data_template:
      brightness: > 
        {{ [(((10 - state_attr('sun.sun', 'elevation')) / 10) * 200)|int(0),state_attr('light.main_lights','brightness')]|max}}

- alias: Lights down (post-sunset)
  trigger:
  - platform: time_pattern
    minutes: /1
  condition:
  - condition: state
    entity_id: person.andrew
    state: home
  - condition: sun
    after: sunset
  - condition: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: -5
    above: -15
  action:
  - service: light.turn_on
    entity_id: light.main_lights
    data_template:
      brightness: > 
        {{ 100 + (((15 + state_attr('sun.sun', 'elevation')) / 10) * 100)|int(0) }}

- alias: Lights down (pre-bedtime)
  trigger:
  - platform: time_pattern
    minutes: /5
  condition:
  - condition: state
    entity_id: person.andrew
    state: home
  - condition: state
    entity_id: switch.bedtime
    state: "on"
  - condition: numeric_state
    entity_id: light.main_lights
    value_template: "{{state_attr('light.main_lights', 'brightness')}}"
    above: 20
  action:
  - service: light.turn_on
    entity_id: light.main_lights
    data_template:
      brightness:
        "{{(state_attr('light.main_lights', 'brightness') - 5)|int(0)}}"
      rgb_color:
      - "{{(state_attr('light.main_lights', 'rgb_color')[0])|int(0) }}"
      - "{{(state_attr('light.main_lights', 'rgb_color')[1]-5)|int(0) }}"
      - "{{(state_attr('light.main_lights', 'rgb_color')[2]-5)|int(0) }}"

- alias: Recognise when it's bedtime
  trigger:
  - platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: time_for_bed
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.bedtime

- alias: Lights up (pre-sunrise)
  trigger:
  - platform: time_pattern
    minutes: /1
  condition:
  - condition: state
    entity_id: switch.bedtime
    state: "on"
  - condition: state
    entity_id: person.andrew
    state: home
  - condition: sun
    after: sunrise
  - condition: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 30
    above: 10
  action:
  - service: light.turn_on
    entity_id: light.main_lights
    data_template:
      brightness: > 
        {{ [(((state_attr('sun.sun', 'elevation')-10) / 20) * 120)|int(0),state_attr('light.main_lights','brightness')]|max}}
      rgb_color:
      - "{{state_attr('light.main_lights', 'rgb_color')[0]*(((state_attr('sun.sun', 'elevation')-10) / 20) * 230)|int(0) }}"
      - "{{state_attr('light.main_lights', 'rgb_color')[1]*(((state_attr('sun.sun', 'elevation')-10) / 20) * 210)|int(0) }}"
      - "{{state_attr('light.main_lights', 'rgb_color')[2]*(((state_attr('sun.sun', 'elevation')-10) / 20) * 210)|int(0) }}"

- alias: Send roomba home when Andrew comes home
  trigger:
  - platform: state
    entity_id: person.andrew
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: vacuum.roomba
    state: 'on'
  action:
  - service: vacuum.return_to_base
    entity_id: vacuum.roomba

- alias: Close the blinds when the sun has set
  trigger:
  - platform: sun
    event: sunset
    offset: 00:00:00
  action:
  - service: cover.close_cover
    entity_id: cover.blinds

- alias: Andrew goes to sleep
  trigger:
  - platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: goodnight
  condition:
  - condition: state
    entity_id: person.andrew
    state: home
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.bedtime
  - service: light.turn_off
    data:
      entity_id: light.all_lights
  - service: light.turn_on
    data:
      entity_id: light.bathroom_bulb_4
      brightness: 30
  - service: light.turn_on
    data:
      entity_id: light.lounge_lamp
      brightness: 30


- alias: Andrew wakes up
  trigger:
  - platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: goodmorning
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.andrew
      state: home
    - condition: time
      after: '6:00'
      before: '23:00'
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.bedtime
  - service: cover.set_cover_position
    entity_id: cover.blinds
    data:
      position: 20
  - service: light.turn_on
    entity_id: light.kitchen
    data:
      brightness: 180
      color_temp: 400
  - service: light.turn_on
    entity_id: light.lounge
    data:
      brightness: 180
      color_temp: 400
  - service: light.turn_on
    entity_id: light.vanity
    data:
      brightness: 100
      color_temp: 400

- alias: Turn off the lights when I leave home
  trigger:
  - platform: state
    entity_id: person.andrew
    from: home
    to: not_home
  action:
  - service: homeassistant.turn_off
    entity_id: light.all_lights
  - service: homeassistant.turn_off
    entity_id: switch.living_room
  - service: ifttt.trigger
    data:
      event: light_living_room_off
  - service: notify.slack
    data:
      message: You left home so I turned the lights off

- alias: Open the blinds when I leave home
  trigger:
  - platform: state
    entity_id: person.andrew
    from: home
    to: not_home
  action:
  - service: cover.open_cover
    entity_id: cover.blinds

- alias: Raise the lights in the morning
  trigger:
  - event: sunrise
    platform: sun
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: person.andrew
      state: home
  action:
  - service: homeassistant.turn_on
    entity_id: scene.morning
  - data:
      message: Good morning, I turned the lights on in the kitchen
    service: notify.slack

- alias: Rainy Day
  trigger:
  - platform: state
    entity_id: sensor.precip_intensity
    to: rain
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: person.andrew
      state: home
  - condition: time
    after: '14:00'
    before: '23:00'
  action:
  - service: homeassistant.turn_on
    entity_id: scene.evening
  - service: notify.slack
    data:
      message: It's raining so I turned the lights on

- alias: Dark Morning
  trigger:
  - platform: numeric_state
    entity_id: sensor.dark_sky_cloud_coverage_0
    above: 70
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: person.andrew
      state: home
  - condition: state
    entity_id: sun.sun
    state: above_horizon
  action:
  - service: homeassistant.turn_on
    entity_id: scene.evening
  - service: notify.slack
    data:
      message: It's dark so I turned the lights on

- alias: Begin vacuuming
  trigger:
  - platform: time
    at: '11:00:00'
  condition:
  - condition: state
    entity_id: person.andrew
    state: not_home
  action:
  - service: vacuum.turn_on
    entity_id: vacuum.roomba
  - service: notify.slack
    data:
      message: I started the Roomba on a cleaning cycle

- alias: Select theme
  id: hass_theme
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_select.hass_theme
  action:
  - service: frontend.set_theme
    data_template:
      name: '{{ states.input_select.hass_theme.state }}'

- alias: Turn off the lights when I go to sleep
  condition:
  - condition: state
    entity_id: person.andrew
    state: home
  trigger:
  - platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: goodnight
  action:
  - service: homeassistant.turn_off
    entity_id: group.all_lights
  - service: light.turn_on
    entity_id: light.vanity
    data:
      brightness: 10

- alias: Andrew arrives home
  id: arrive_home
  trigger:
  - platform: state
    entity_id: person.andrew
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: person.andrew
    state: home
  action:
  - service: script.raise_lights

- alias: Smoke
  id: smoke
  trigger:
  - platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: smoke
  action:
  - service: cover.set_cover_position
    entity_id: cover.left_blind
    data:
      position: 70

- alias: Movie time
  id: movie_time
  trigger:
  - platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: movie_time
  action:
  - service: light.turn_on
    entity_id: light.kitchen
    data:
      brightness: 60
  - service: light.turn_on
    entity_id: light.bedroom
    data:
      brightness: 50
  - service: light.turn_on
    entity_id: light.lounge
    data:
      brightness: 30
  - service: light.turn_on
    entity_id: light.lounge_lamp
    data:
      brightness: "{{ [state_attr('light.lounge_lamp','brightness'),20]|min}}"
  - service: light.turn_off
    entity_id: light.spot