homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 40.7800486
  longitude: -73.9523596
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: -36
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

system_health:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#        base_url: http://home.andrew-myhre.com:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

zone:
  - name: Home
    latitude: 40.7800486
    longitude: -73.9523596
    radius: 40
    icon: mdi:home
  - name: Work
    latitude: 40.739611
    longitude: -73.992365
    radius: 50
    icon: mdi:office-building


# Track the sun
sun:

# Sensors
sensor: !include sensors.yaml

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:
  alexa:
    filter:
      include_entities:
        - light.hallway
        - light.doorway
        - light.kitchen
        - media_player.roku
        - media_player.tv_ha
        - scene.movie
        - scene.evening
        - scene.kitchenlow
        - scene.kitchenhigh
        - scene.eveninglow

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

device_tracker:
  - platform: quantum_gateway
    host: 192.168.1.1
    password: door316wax
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false
    interval_seconds: 10
    consider_home: 300
  - platform: bluetooth_le_tracker
    interval_seconds: 10
    consider_home: 300
  - platform: bluetooth_tracker
    interval_seconds: 10
    consider_home: 300
  - platform: nmap_tracker
    hosts: 192.168.1.0/24

# notify:
#   - name: slack
#     platform: slack
#     api_key: 
#     default_channel: '#andrew-is-awesome'
#     username: "@homeassistant"
#     icon: ":house:"

tplink:

light:
  - platform: limitlessled
    bridges:
      - host: 192.168.1.195
        groups:
        - number: 1
          type: rgbww
          name: Doorway
          fade: true
        - number: 2
          type: rgbww
          name: Hallway
        - number: 3
          type: rgbww
          name: Kitchen
          fade: true
  - platform: group
    entities:
      - light.bedroom_light_1
    name: Bedroom
  - platform: group
    name: Kitchen
    entities:
      - light.kitchen_light_1
      - light.kitchen_light_2
  - platform: group
    name: Lounge
    entities:
      - light.lounge_light_1
      - light.lounge_light_2
      - light.lounge_light_3


media_player:
  - platform: roku
  - platform: samsungtv
    host: 192.168.1.5
    port: 8001
    name: tv_ha
switch livingroom:
  - platform: tplink
    host: 192.168.1.217
    name: "Living Room"
scene:
  - name: morning
    entities: 
      light.hallway:
        state: true
        color_name: "Warm White"
        brightness: 194
  - name: Movie
    entities: 
      light.hallway:
        state: true
        color_temp: 454
        brightness: 26
      light.doorway:
        state: true
        brightness: 26
        color_temp: 454
      switch.living_room:
        state: false
  - name: LowLights
    entities:
      switch.living_room:
        state: true
      light.kitchen:
        state: true
        brightness: 60
        color_temp: 454
      light.bedroom:
        brightness: 35
        color_temp: 60
        state: true
  - name: EveningLow
    entities:
      switch.living_room:
        state: true
      light.kitchen:
        state: true
        brightness: 190
        color_temp: 454
      light.bedroom:
        brightness: 35
        color_temp: 454
        state: true

  - name: Evening
    entities:
      light.kitchen:
        state: true
        brightness: 150
        color_name: "Warm White"
      light.bedroom:
        brightness: 35
        color_temp: 2500
        state: true
      light.lounge:
        state: true
        brightness: 89
        color_name: "Warm White"

  - name: Evening2
    entities:
      light.kitchen:
        state: true
        brightness: 140
        color_name: "Warm White"
        transition: 60
      light.bedroom:
        brightness: 35
        color_temp: 2500
        state: true
      light.lounge:
        state: true
        brightness: 80
        color_name: "Warm White"


  - name: Evening3
    entities:
      light.kitchen:
        state: true
        brightness: 130
        color_name: "Warm White"
        transition: 60
      light.bedroom:
        brightness: 35
        color_temp: 2500
        state: true
      light.lounge:
        state: true
        brightness: 70
        color_name: "Warm White"

  - name: Evening4
    entities:
      light.kitchen:
        state: true
        brightness: 120
        color_name: "Warm White"
        transition: 60
      light.bedroom:
        brightness: 35
        color_temp: 2500
        state: true
      light.lounge:
        state: true
        brightness: 60
        color_name: "Warm White"

  - name: Evening5
    entities:
      light.kitchen:
        state: true
        brightness: 110
        color_name: "Warm White"
        transition: 60
      light.bedroom:
        brightness: 35
        color_temp: 2500
        state: true
      light.lounge:
        state: true
        brightness: 50
        color_name: "Warm White"

  - name: Evening6
    entities:
      light.kitchen:
        state: true
        brightness: 100
        color_name: "Warm White"
        transition: 60
      light.bedroom:
        brightness: 35
        color_temp: 2500
        state: true
      light.lounge:
        state: true
        brightness: 40
        color_name: "Warm White"

  - name: Evening7
    entities:
      light.kitchen:
        state: true
        brightness: 90
        color_name: "Warm White"
        transition: 60
      light.bedroom:
        brightness: 35
        color_temp: 2500
        state: true
      light.lounge:
        state: true
        brightness: 30
        color_name: "Warm White"

  - name: Evening8
    entities:
      light.kitchen:
        state: true
        brightness: 80
        color_name: "Warm White"
        transition: 60
      light.bedroom:
        brightness: 35
        color_temp: 2500
        state: true
      light.lounge:
        state: true
        brightness: 20
        color_name: "Warm White"

  - name: Evening9
    entities:
      light.kitchen:
        transition: 60
        state: true
        brightness: 70
        color_name: "Warm White"
      light.bedroom:
        brightness: 35
        color_temp: 2500
        state: true
      light.lounge:
        state: true
        brightness: 10
        color_name: "Warm White"

  - name: Evening10
    entities:
      light.kitchen:
        state: true
        brightness: 10
        color_name: "Warm White"
        transition: 60
      light.bedroom:
        brightness: 10
        color_temp: 2500
        state: true
      light.lounge:
        state: true
        brightness: 10
        color_name: "Warm White"

  - name: AllLightsOff
    entities:
      light.lounge:
        state: false
        color_name: "Warm White"
        brightness: 0
      light.kitchen:
        state: false
        color_name: "Warm White"
        brightness: 0
      light.bedroom:
        state: false
        color_name: Warm White"
        brightness: 0
  - name: kitchenlow
    entities:
      light.kitchen:
        state: true
        brightness: 25
        color_temp: 370
    friendly_name: "Kitchen Low"
    alexa_description: "Kitchen Low"
    alexa_display_categories: "SCENE"
    alexa_hidden: false
  - name: kitchenhigh
    entities:
      light.kitchen:
        state: true
        brightness: 200
        color_temp: 454
    friendly_name: "Kitchen High"
    alexa_description: "Kitchen High"
    alexa_display_categories: "SCENE"
    alexa_hidden: false

ifttt:
  key: bD9EVd6gCvWCIw9JEUoZk7

tuya:
  username: "andrew.myhre@gmail.com"
  password: "Z2@#CNNg^eHH9dz6TGQ"
  country_code: "1"

vacuum:
  - platform: roomba
    host: 192.168.1.9
    username: 3175000031817670
    password: ":1:1575845387:taEElBRsoG0VTOHW"

weather:
  - platform: darksky
    api_key: 67ddd9c4685908120132aaa3253821f7
    mode: daily

input_select:
  hass_theme:
    name: HASS Themes
    options:
      - default
      - amoled
      - dark
      - sublimation
      - darkred
      - darkcyan
      - midnight
      - darkorange
      - material_dark_green
      - slate
      - solarized_dark
      - solarized_light
      - teal
    initial: default
    icon: mdi:theme-light-dark

camera:
  - platform: generic
    name: Living room cam
    still_image_url: http://127.0.0.1:8081
#    mjpeg_url: http://127.0.0.1:8081
    stream_source: http://127.0.0.1:8081

stream:
