homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 40.769760
  longitude: -73.954580
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 200
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: EST
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
   base_url: home.andrew-myhre.com:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:
  alexa:
    filter:
      include_entities:
        - light.hallway
        - light.doorway
        - light.kitchen
        - media_player.roku
        - media_player.tv_ha
        - scene.movie
        - scene.evening

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

light:
  - platform: limitlessled
    bridges:
      - host: 192.168.1.195
        groups:
        - number: 1
          type: rgbww
          name: Doorway
          fade: true
        - number: 2
          type: rgbww
          name: Hallway
        - number: 3
          type: rgbww
          name: Kitchen
          fade: true
  - platform: tplink
    host: 192.168.1.192
    name: Bedroom
media_player:
  - platform: roku
  - platform: samsungtv
    host: 192.168.1.5
    port: 8001
    name: tv_ha
switch:
  - platform: tplink
    host: 192.168.1.203
    name: "Living Room"
scene:
  - name: Movie
    entities: 
      light.hallway:
        state: true
        rgb_color: 255,255,72
        brightness: 26
      switch.living_room:
        state: false
  - name: Evening
    entities:
      light.hallway:
        state: true
        rgb_color: 255,255,72
        brightness: 150
      switch.living_room:
        state: true

