- platform: yr
- platform: darksky
  api_key: 67ddd9c4685908120132aaa3253821f7
  forecast:
    - 1
    - 2
    - 3
    - 4
    - 5
  monitored_conditions:
    - summary
    - icon
    - temperature
    - precip_intensity
    - precip_probability
    - precip_type
    - precip_accumulation
    - temperature
    - apparent_temperature
    - wind_speed
    - wind_gust
    - minutely_summary
    - hourly_summary
    - daily_summary
    - sunrise_time
    - sunset_time
    - cloud_cover
    - alerts

- platform: template
  sensors:
    roomba_battery_level:
      value_template: >
        {{ states.vacuum.the_dog.attributes.battery_level }}
      friendly_name: Battery Level
      unit_of_measurement: '%'
      icon_template: '{{ states.vacuum.the_dog.attributes.battery_icon }}'

- platform: template
  sensors:
    roomba_current_status:
      value_template: >
        {{ states.vacuum.the_dog.attributes.status }}
      friendly_name: Status

- platform: template
  sensors:
    roomba_bin_full:
      value_template: >-
        {% if is_state('status.vacuum.the_dog.attributes.bin_full', 'true') %}
        Bin is full
        {% else %}
        Bin is not full
        {% endif %}
      friendly_name: Bin full

- platform: template
  sensors:
    roomba_status:
      value_template: >
        {% if is_state('status.vacuum.the_dog.attributes.bin_full', 'true') %}
        {{ states.vacuum.the_dog.attributes.status }}

        Bin is full
        {% else %}
        {{ states.vacuum.the_dog.attributes.status }}

        Bin is not full
        {% endif %}
      icon_template: '{{ states.vacuum.the_dog.attributes.battery_icon }}'
      friendly_name_template: '{{ states.vacuum.the_dog.attributes.battery_level }}%'


- platform: template
  sensors:
    main_lights_brightness:
      friendly_name: Main lights brightness
      value_template: >
        {{ states.light.main_lights.attributes.brightness}}
      unit_of_measurement: ms

- platform: template
  sensors:
    sun_elevation:
      friendly_name: Sun elevation
      value_template: >
        {{ states.sun.sun.attributes.elevation}}
      unit_of_measurement: s